import type { GeneratorConfig } from "../types";
import {
  getLanguageFileExtensions,
  getPackageManagerInstallCommand,
  getPackageManagerScriptCommand,
} from "./shared";

export function buildEnvExample(cfg: GeneratorConfig): string {
  const lines: string[] = [
    "# Application",
    "NEXT_PUBLIC_APP_URL=http://localhost:3000",
    "NEXT_PUBLIC_APP_NAME=" + cfg.projectName,
    "",
  ];

  if (cfg.auth === "nextauth") {
    lines.push("# NextAuth.js");
    lines.push('NEXTAUTH_URL="http://localhost:3000"');
    lines.push('NEXTAUTH_SECRET=""  # openssl rand -base64 32');
    lines.push("");
  }
  if (cfg.auth === "jwt") {
    lines.push("# JWT");
    lines.push('JWT_SECRET=""  # openssl rand -base64 32');
    lines.push('JWT_EXPIRES_IN="7d"');
    lines.push("");
  }
  if (cfg.database === "postgresql") {
    lines.push("# PostgreSQL");
    lines.push(
      'DATABASE_URL="postgresql://postgres:password@localhost:5432/' +
        cfg.projectName.replace(/-/g, "_") +
        '"',
    );
    lines.push("");
  }
  if (cfg.database === "mongodb") {
    lines.push("# MongoDB");
    lines.push(
      'MONGODB_URI="mongodb://root:password@localhost:27017/' +
        cfg.projectName +
        '?authSource=admin"',
    );
    lines.push("");
  }
  if (cfg.apiLayer === "graphql") {
    lines.push("# GraphQL");
    lines.push("NEXT_PUBLIC_GRAPHQL_URL=http://localhost:3000/api/graphql");
    lines.push("");
  }

  return lines.join("\n");
}

export function buildAppLayout(cfg: GeneratorConfig): string {
  const { isTypeScript } = getLanguageFileExtensions(cfg.language);
  const tailwind = cfg.styling === "tailwind";
  return `${isTypeScript ? 'import type { Metadata } from "next";\n' : ""}import { Inter } from "next/font/google";
${tailwind ? `import "./globals.css";` : ""}

const inter = Inter({ subsets: ["latin"] });

export const metadata${isTypeScript ? ": Metadata" : ""} = {
  title: {
    default: "${cfg.projectName}",
    template: \`%s | ${cfg.projectName}\`,
  },
  description: "Generated by Next.js Starter",
};

export default function RootLayout({
  children,
}${isTypeScript ? ": { children: React.ReactNode }" : ""}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`;
}

export function buildAppPage(cfg: GeneratorConfig): string {
  void cfg;
  return `export default function Home() {
  return (
    <main>
      <h1>${cfg.projectName}</h1>
      <p>Welcome to your new Next.js app.</p>
    </main>
  );
}
`;
}

export function buildMiddleware(cfg: GeneratorConfig): string {
  const { isTypeScript } = getLanguageFileExtensions(cfg.language);
  const ext = isTypeScript ? "ts" : "js";
  void ext;
  return `import { NextResponse } from "next/server";
${isTypeScript ? 'import type { NextRequest } from "next/server";\n' : ""}

export function middleware(request${isTypeScript ? ": NextRequest" : ""}) {
  // Add custom middleware logic here
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    "/((?!api|_next/static|_next/image|favicon.ico).*)",
  ],
};
`;
}

export function buildApiLib(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `${ts ? "interface FetchOptions extends RequestInit {\n  params?: Record<string, string>;\n}\n\n" : ""}const BASE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export async function apiFetch${ts ? "<T = unknown>" : ""}(
  path${ts ? ": string" : ""},
  options${ts ? ": FetchOptions" : ""} = {}
)${ts ? ": Promise<T>" : ""} {
  const { params, ...init } = options${ts ? " as FetchOptions" : ""} ?? {};
  const url = new URL(path, BASE_URL);
  if (params) {
    Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));
  }

  const res = await fetch(url.toString(), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init.headers,
    },
  });

  if (!res.ok) {
    throw new Error(\`API Error \${res.status}: \${res.statusText}\`);
  }

  return res.json()${ts ? " as Promise<T>" : ""};
}

export const api = {
  get: ${ts ? "<T>(path: string, options?: FetchOptions) => " : ""}apiFetch${ts ? "<T>" : ""}(path, { method: "GET", ...options }),
  post: ${ts ? "<T>(path: string, body: unknown, options?: FetchOptions) => " : ""}apiFetch${ts ? "<T>" : ""}(path, { method: "POST", body: JSON.stringify(body), ...options }),
  put: ${ts ? "<T>(path: string, body: unknown, options?: FetchOptions) => " : ""}apiFetch${ts ? "<T>" : ""}(path, { method: "PUT", body: JSON.stringify(body), ...options }),
  delete: ${ts ? "<T>(path: string, options?: FetchOptions) => " : ""}apiFetch${ts ? "<T>" : ""}(path, { method: "DELETE", ...options }),
};
`;
}

export function buildErrorLib(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `${ts ? 'export class AppError extends Error {\n  constructor(\n    message: string,\n    public readonly code: string = "INTERNAL_ERROR",\n    public readonly status: number = 500,\n  ) {\n    super(message);\n    this.name = "AppError";\n  }\n}\n\n' : ""}export function isAppError(error${ts ? ": unknown" : ""})${ts ? ": error is AppError" : ""} {
  return error instanceof ${ts ? "AppError" : "Error"} && "code" in error;
}

export function getErrorMessage(error${ts ? ": unknown" : ""})${ts ? ": string" : ""} {
  if (error instanceof Error) return error.message;
  return String(error);
}
`;
}

export function buildLoggerLib(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `${ts ? 'type LogLevel = "debug" | "info" | "warn" | "error";\n\n' : ""}const isDev = process.env.NODE_ENV === "development";

function createLogger() {
  function log(level${ts ? ": LogLevel" : ""}, message${ts ? ": string" : ""}, meta${ts ? ": Record<string, unknown>" : ""} = {}) {
    if (level === "debug" && !isDev) return;
    const entry = { level, message, timestamp: new Date().toISOString(), ...meta };
    if (level === "error") {
      console.error(JSON.stringify(entry));
    } else {
      console.log(JSON.stringify(entry));
    }
  }

  return {
    debug: (msg${ts ? ": string" : ""}, meta${ts ? "?: Record<string, unknown>" : ""}) => log("debug", msg, meta),
    info: (msg${ts ? ": string" : ""}, meta${ts ? "?: Record<string, unknown>" : ""}) => log("info", msg, meta),
    warn: (msg${ts ? ": string" : ""}, meta${ts ? "?: Record<string, unknown>" : ""}) => log("warn", msg, meta),
    error: (msg${ts ? ": string" : ""}, meta${ts ? "?: Record<string, unknown>" : ""}) => log("error", msg, meta),
  };
}

export const logger = createLogger();
`;
}

export function buildPrismaLib(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis${ts ? " as unknown as { prisma: PrismaClient }" : ""};

export const prisma${ts ? ": PrismaClient" : ""} = globalForPrisma.prisma ?? new PrismaClient({
  log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
});

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`;
}

export function buildPrismaSchema(cfg: GeneratorConfig): string {
  const provider = cfg.database === "postgresql" ? "postgresql" : "mongodb";
  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(${provider === "mongodb" ? "auto()" : "cuid()"})${provider === "mongodb" ? '\n  @map("_id")' : ""}
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`;
}

export function buildStoreFile(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  if (cfg.stateManagement === "zustand") {
    return `import { create } from "zustand";
import { devtools } from "zustand/middleware";

${ts ? "interface AppState {\n  count: number;\n  increment: () => void;\n  decrement: () => void;\n  reset: () => void;\n}\n\n" : ""}export const useAppStore = create${ts ? "<AppState>" : ""}()(
  devtools(
    (set) => ({
      count: 0,
      increment: () => set((state) => ({ count: state.count + 1 })),
      decrement: () => set((state) => ({ count: state.count - 1 })),
      reset: () => set({ count: 0 }),
    }),
    { name: "AppStore" }
  )
);
`;
  }

  if (cfg.stateManagement === "redux-toolkit") {
    return `import { configureStore } from "@reduxjs/toolkit";

export const store = configureStore({
  reducer: {
    // Add your slice reducers here
  },
});

${ts ? "export type RootState = ReturnType<typeof store.getState>;\nexport type AppDispatch = typeof store.dispatch;\n" : ""}`;
  }

  return `// React Context store placeholder\n// Add your context providers here.\n`;
}

export function buildHook(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `import { useState, useEffect } from "react";

export function useLocalStorage${ts ? "<T>" : ""}(key${ts ? ": string" : ""}, initialValue${ts ? ": T" : ""}) {
  const [storedValue, setStoredValue] = useState${ts ? "<T>" : ""}(() => {
    if (typeof window === "undefined") return initialValue;
    try {
      const item = window.localStorage.getItem(key);
      return item ? (JSON.parse(item)${ts ? " as T" : ""}) : initialValue;
    } catch {
      return initialValue;
    }
  });

  const setValue = (value${ts ? ": T | ((val: T) => T)" : ""}) => {
    try {
      const valueToStore = value instanceof Function ? value(storedValue) : value;
      setStoredValue(valueToStore);
      if (typeof window !== "undefined") {
        window.localStorage.setItem(key, JSON.stringify(valueToStore));
      }
    } catch (error) {
      console.error(error);
    }
  };

  return [storedValue, setValue]${ts ? " as const" : ""};
}
`;
}

export function buildAtomButton(cfg: GeneratorConfig): string {
  const { isTypeScript: ts } = getLanguageFileExtensions(cfg.language);
  return `import React from "react";
${ts ? '\ninterface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\n  variant?: "primary" | "secondary" | "ghost";\n  size?: "sm" | "md" | "lg";\n  isLoading?: boolean;\n}\n' : ""}
export function Button({
  children,
  variant = "primary",
  size = "md",
  isLoading = false,
  className = "",
  disabled,
  ...props
}${ts ? ": ButtonProps" : ""}) {
  return (
    <button
      disabled={disabled ?? isLoading}
      className={\`btn btn--\${variant} btn--\${size} \${className}\`}
      {...props}
    >
      {isLoading ? "Loading..." : children}
    </button>
  );
}
`;
}

export function buildReadme(cfg: GeneratorConfig): string {
  const pm = cfg.packageManager;
  const install = getPackageManagerInstallCommand(pm).replace(" --frozen-lockfile", "");
  const devCommand = getPackageManagerScriptCommand(pm, "dev");
  const buildCommand = getPackageManagerScriptCommand(pm, "build");
  const startCommand = getPackageManagerScriptCommand(pm, "start");
  const lintCommand = getPackageManagerScriptCommand(pm, "lint");
  const testCommand = getPackageManagerScriptCommand(pm, "test");
  const dbGenerateCommand = getPackageManagerScriptCommand(pm, "db:generate");

  return `# ${cfg.projectName}

A Next.js ${cfg.nextVersion} application generated by [Next.js Starter](https://starter-nextjs.vercel.app).

## Stack

- **Framework**: Next.js ${cfg.nextVersion} (${cfg.router === "app" ? "App Router" : "Pages Router"})
- **Language**: ${cfg.language === "typescript" ? "TypeScript" : "JavaScript"}
- **Styling**: ${cfg.styling}
- **State**: ${cfg.stateManagement}
- **Auth**: ${cfg.auth}
- **Database**: ${cfg.database}${cfg.orm !== "none" ? ` + ${cfg.orm}` : ""}
- **Testing**: ${cfg.testing}

## Getting Started

\`\`\`bash
${install}
\`\`\`

\`\`\`bash
cp .env.example .env.local
\`\`\`

${cfg.orm === "prisma" ? `\`\`\`bash\n${dbGenerateCommand}\n\`\`\`\n\n` : ""}\`\`\`bash
${devCommand}
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Structure

\`\`\`
src/
├── app/           # Next.js App Router
├── components/    # Atomic Design components
│   ├── atoms/
│   ├── molecules/
│   ├── organisms/
│   └── templates/
├── features/      # Feature-based modules
├── hooks/         # Reusable React hooks
├── lib/           # Third-party lib setup + utilities
├── store/         # State management
├── types/         # Shared TypeScript types
└── utils/         # Pure utility functions
\`\`\`

## Scripts

| Command | Description |
|---------|-------------|
| \`${devCommand}\` | Start development server |
| \`${buildCommand}\` | Build for production |
| \`${startCommand}\` | Start production server |
| \`${lintCommand}\` | Run ESLint |
${cfg.testing !== "none" ? `| \`${testCommand}\` | Run tests |\n` : ""}
`;
}
